name: generate
on:
  # workflow_dispatch:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout for Github repository workspace
        uses: actions/checkout@v4

      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install python requirements packages
        run: pip install -r scripts/requirements.txt

      - name: Start generate...
        run: python scripts/generate.py

      - uses: actions/upload-artifact@v3
        with:
          name: MKVerilog-lib.zip
          path: out
