name: release

on:
  workflow_dispatch:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/generate.yaml
    secrets: inherit
    with:
      releaseVersion: ${{ github.ref_name }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
    # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
    concurrency:
      group: github-release
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.FILE_NAME }}
          path: out

      # https://github.com/mikepenz/release-changelog-builder-action
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        run: |
          echo Ref Name: ${{ github.ref_name }}
          zip -r MKVerilog-lib-${{ github.ref_name }}.zip out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          files: MKVerilog-lib-${{ github.ref_name }}.zip
